version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: graph_visualize

  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    ports:
      - "7474:7474"  
      - "7687:7687"   
    environment:
      - NEO4J_AUTH=neo4j/12345678  
    volumes:
      - neo4j_data:/data

  python_service:
    build:
      context: ./python_service
    container_name: python_service
    ports:
      - "8000:8000"
    volumes:
      - ./python_service:/app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test123

volumes:
  mongo_data:
  neo4j_data:
